const translations = {
  en: {
    nav_services: 'Services',
    nav_pricing: 'Pricing',
    nav_how: 'How it works',
    nav_business: 'Business',
    nav_contact: 'Contact',
    eyebrow: 'Personalized laundry support in Zug',
    hero_title: 'Oriella Laundry & Care',
    hero_tagline: 'your laundry our care',
    hero_lead: 'Personalized laundry support designed to make everyday life easier. Reliable, flexible and professional care for your clothes, adapted to your needs.',
    free_delivery_title: 'Free pickup & delivery',
    free_delivery_text: 'for private clients in Zug and surrounding areas.',
    btn_book: 'Book Pickup',
    btn_whatsapp: 'WhatsApp Us',
    btn_quote: 'Request a Quote',
    intro_title: 'Laundry care that fits real life',
    intro_text: 'At Oriella, we understand that laundry is part of daily life, but it should not become daily stress. Our goal is to make your routine lighter with a flexible and personalized service you can trust.',
    why_label: 'Why choose Oriella',
    why_title: 'Personal care, not just laundry',
    why_1_title: 'Personalized service',
    why_1_text: 'Support adapted to your routine, your needs and your preferences.',
    why_2_title: 'Flexible scheduling',
    why_2_text: 'Service arranged based on availability and what works best for you.',
    why_3_title: 'Free pickup & delivery',
    why_3_text: 'Convenient collection and return included for private clients in the service area.',
    why_4_title: 'Private & business clients',
    why_4_text: 'Suitable for homes, busy professionals and businesses with recurring needs.',
    services_label: 'Our services',
    services_title: 'Practical support for everyday laundry needs',
    service_1_title: 'Everyday Laundry',
    service_1_text: 'Care for daily clothing with consistency, freshness and attention.',
    service_2_title: 'Wash & Fold',
    service_2_text: 'Clean, fresh and neatly prepared laundry ready to use.',
    service_3_title: 'Shirts & Ironing',
    service_3_text: 'Shirt ironing available as an add-on or full service for shirts only.',
    service_4_title: 'Duvets & Pillows',
    service_4_text: 'Washing for duvets and pillows is also possible. Price on request.',
    service_5_title: 'Free Pickup & Delivery',
    service_5_text: 'Free collection and return for private clients, depending on location and availability.',
    service_6_title: 'Personalized Requests',
    service_6_text: 'Other garment types are possible. Prices available on request.',
    pricing_label: 'Private client pricing',
    pricing_title: 'Simple pricing for everyday laundry',
    pricing_subtitle: 'Transparent base prices for private clients. Other items and special requests can be quoted individually.',
    price_everyday_label: 'Everyday laundry',
    price_5kg_title: 'Up to 5 kg',
    price_5kg_text: 'Ideal for smaller bags of daily laundry.',
    price_everyday_label_2: 'Everyday laundry',
    price_8kg_title: 'Up to 8 kg',
    price_8kg_text: 'A practical option for larger weekly loads.',
    price_extra_label: 'Additional weight',
    price_extra_title: 'After 8 kg',
    price_extra_text: 'For laundry loads above 8 kg.',
    shirts_addon_title: 'Shirts from the laundry bag',
    shirts_addon_text: 'Ironing only, when the washing has already been included in the bag service.',
    shirts_full_title: 'Shirts only',
    shirts_full_text: 'Wash, dry and iron service for shirts only.',
    duvets_title: 'Duvets & pillows',
    price_on_request: 'On request',
    duvets_text: 'Also possible. Price depends on item and size.',
    note_pickup_title: 'Free pickup & delivery',
    note_pickup_text: 'Included for private clients within the service area.',
    note_other_title: 'Other items',
    note_other_text: 'Other garment types and special requests are possible. Price on request.',
    how_label: 'How it works',
    how_title: 'Simple, flexible and stress-free',
    step_1_title: 'Contact us',
    step_1_text: 'Message us by WhatsApp, email or Instagram.',
    step_2_title: 'Tell us what you need',
    step_2_text: 'Share the type of laundry, your location and your preferred timing.',
    step_3_title: 'We confirm the best option',
    step_3_text: 'We arrange the service based on your needs, availability and service area.',
    step_4_title: 'Enjoy more time for yourself',
    step_4_text: 'Oriella takes care of your laundry so you can focus on what matters most.',
    area_label: 'Service area',
    area_title: 'Zug and surrounding areas',
    area_text: 'Oriella serves Zug and nearby locations within around 20 km. Other areas may also be possible on request, with adjusted pricing depending on distance and service needs.',
    area_box: 'Any locality outside the main area can be discussed individually.',
    business_label: 'For businesses',
    business_title: 'Laundry support adapted to each business',
    business_text: 'Business pricing may vary depending on laundry volume, frequency, item types, pickup and delivery needs, and location. For business services, please request a personalized quote.',
    business_btn: 'Request Business Quote',
    cta_title: 'Make daily life easier with Oriella',
    cta_text: 'Laundry is part of life, but it does not have to take your time and energy. Oriella Laundry & Care is here to offer reliable, flexible and personalized support you can count on.',
    cta_btn_1: 'Contact on WhatsApp',
    cta_btn_2: 'Send Email',
    footer_text: 'Flexible hours depending on availability and client needs.',
    footer_contact: 'Contact',
    footer_location: 'Location',
    footer_location_text: 'Zug and surrounding areas'
  },
  de: {
    nav_services: 'Leistungen',
    nav_pricing: 'Preise',
    nav_how: 'Ablauf',
    nav_business: 'Geschäftskunden',
    nav_contact: 'Kontakt',
    eyebrow: 'Persönlicher Wäscheservice in Zug',
    hero_title: 'Oriella Laundry & Care',
    hero_tagline: 'your laundry our care',
    hero_lead: 'Persönlicher Wäscheservice, der den Alltag leichter macht. Zuverlässige, flexible und professionelle Pflege für Ihre Kleidung – abgestimmt auf Ihre Bedürfnisse.',
    free_delivery_title: 'Kostenlose Abholung & Lieferung',
    free_delivery_text: 'für Privatkunden in Zug und Umgebung.',
    btn_book: 'Abholung buchen',
    btn_whatsapp: 'Per WhatsApp',
    btn_quote: 'Offerte anfragen',
    intro_title: 'Wäschepflege, die ins echte Leben passt',
    intro_text: 'Bei Oriella wissen wir, dass Wäsche zum Alltag gehört – aber nicht zum täglichen Stress werden sollte. Unser Ziel ist es, Ihren Alltag mit einem flexiblen und persönlichen Service spürbar zu erleichtern.',
    why_label: 'Warum Oriella',
    why_title: 'Persönliche Betreuung, nicht nur Wäsche',
    why_1_title: 'Persönlicher Service',
    why_1_text: 'Unterstützung, die sich an Ihrem Alltag, Ihren Bedürfnissen und Ihren Wünschen orientiert.',
    why_2_title: 'Flexible Planung',
    why_2_text: 'Der Service wird nach Verfügbarkeit und passend zu Ihrem Alltag organisiert.',
    why_3_title: 'Kostenlose Abholung & Lieferung',
    why_3_text: 'Bequeme Abholung und Rückgabe für Privatkunden im Einsatzgebiet inklusive.',
    why_4_title: 'Privat- & Geschäftskunden',
    why_4_text: 'Geeignet für Haushalte, vielbeschäftigte Menschen und Unternehmen mit wiederkehrendem Bedarf.',
    services_label: 'Unsere Leistungen',
    services_title: 'Praktische Unterstützung für die tägliche Wäsche',
    service_1_title: 'Alltagswäsche',
    service_1_text: 'Pflege für tägliche Kleidung mit Konstanz, Frische und Aufmerksamkeit.',
    service_2_title: 'Waschen & Falten',
    service_2_text: 'Saubere, frische und ordentlich vorbereitete Wäsche – direkt bereit zur Nutzung.',
    service_3_title: 'Hemden & Bügelservice',
    service_3_text: 'Hemden bügeln als Zusatzleistung oder kompletter Service nur für Hemden.',
    service_4_title: 'Duvets & Kissen',
    service_4_text: 'Waschen von Duvets und Kissen ist ebenfalls möglich. Preis auf Anfrage.',
    service_5_title: 'Kostenlose Abholung & Lieferung',
    service_5_text: 'Kostenlose Abholung und Rückgabe für Privatkunden, je nach Ort und Verfügbarkeit.',
    service_6_title: 'Individuelle Anfragen',
    service_6_text: 'Weitere Kleidungsstücke sind möglich. Preise auf Anfrage.',
    pricing_label: 'Preise für Privatkunden',
    pricing_title: 'Einfache Preise für Alltagswäsche',
    pricing_subtitle: 'Klare Grundpreise für Privatkunden. Weitere Stücke und Sonderwünsche werden individuell offeriert.',
    price_everyday_label: 'Alltagswäsche',
    price_5kg_title: 'Bis 5 kg',
    price_5kg_text: 'Ideal für kleinere Säcke mit täglicher Wäsche.',
    price_everyday_label_2: 'Alltagswäsche',
    price_8kg_title: 'Bis 8 kg',
    price_8kg_text: 'Eine praktische Option für grössere Wochenmengen.',
    price_extra_label: 'Zusätzliches Gewicht',
    price_extra_title: 'Ab 8 kg',
    price_extra_text: 'Für Wäschemengen über 8 kg.',
    shirts_addon_title: 'Hemden aus dem Wäschesack',
    shirts_addon_text: 'Nur bügeln, wenn das Waschen bereits im Sackservice enthalten war.',
    shirts_full_title: 'Nur Hemden',
    shirts_full_text: 'Waschen, trocknen und bügeln nur für Hemden.',
    duvets_title: 'Duvets & Kissen',
    price_on_request: 'Auf Anfrage',
    duvets_text: 'Ebenfalls möglich. Der Preis hängt vom Stück und von der Grösse ab.',
    note_pickup_title: 'Kostenlose Abholung & Lieferung',
    note_pickup_text: 'Für Privatkunden im Einsatzgebiet inklusive.',
    note_other_title: 'Weitere Stücke',
    note_other_text: 'Weitere Kleidungsstücke und individuelle Wünsche sind möglich. Preis auf Anfrage.',
    how_label: 'So funktioniert es',
    how_title: 'Einfach, flexibel und stressfrei',
    step_1_title: 'Kontakt aufnehmen',
    step_1_text: 'Schreiben Sie uns per WhatsApp, E-Mail oder Instagram.',
    step_2_title: 'Bedarf mitteilen',
    step_2_text: 'Teilen Sie uns mit, welche Wäsche es ist, wo Sie sind und wann es für Sie passt.',
    step_3_title: 'Beste Option bestätigen',
    step_3_text: 'Wir organisieren den Service passend zu Bedarf, Verfügbarkeit und Einsatzgebiet.',
    step_4_title: 'Mehr Zeit für sich',
    step_4_text: 'Oriella kümmert sich um Ihre Wäsche, damit Sie sich auf Wichtiges konzentrieren können.',
    area_label: 'Einsatzgebiet',
    area_title: 'Zug und Umgebung',
    area_text: 'Oriella bedient Zug und umliegende Orte in einem Radius von etwa 20 km. Andere Standorte sind auf Anfrage ebenfalls möglich, mit angepasstem Preis je nach Distanz und Bedarf.',
    area_box: 'Orte ausserhalb des Hauptgebiets können individuell besprochen werden.',
    business_label: 'Für Unternehmen',
    business_title: 'Wäscheservice passend zu jedem Betrieb',
    business_text: 'Die Preise für Geschäftskunden richten sich nach Wäschemenge, Häufigkeit, Textilart, Abhol- und Lieferbedarf sowie Standort. Für Geschäftskunden erstellen wir gerne eine individuelle Offerte.',
    business_btn: 'Business-Offerte anfragen',
    cta_title: 'Machen Sie den Alltag leichter mit Oriella',
    cta_text: 'Wäsche gehört zum Leben, sollte aber nicht unnötig Zeit und Energie kosten. Oriella Laundry & Care bietet Ihnen zuverlässige, flexible und persönliche Unterstützung, auf die Sie zählen können.',
    cta_btn_1: 'WhatsApp Kontakt',
    cta_btn_2: 'E-Mail senden',
    footer_text: 'Flexible Zeiten je nach Verfügbarkeit und Kundenbedarf.',
    footer_contact: 'Kontakt',
    footer_location: 'Standort',
    footer_location_text: 'Zug und Umgebung'
  }
};

const langButtons = document.querySelectorAll('.lang-btn');
const i18nNodes = document.querySelectorAll('[data-i18n]');

function setLanguage(lang) {
  document.documentElement.lang = lang;
  i18nNodes.forEach(node => {
    const key = node.dataset.i18n;
    if (translations[lang][key]) {
      node.innerHTML = translations[lang][key];
    }
  });
  langButtons.forEach(btn => btn.classList.toggle('active', btn.dataset.lang === lang));
  localStorage.setItem('oriellaLang', lang);
}

langButtons.forEach(btn => {
  btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
});

setLanguage(localStorage.getItem('oriellaLang') || 'en');
